config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # site root

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/#{routes_name}.rb")))
  end

  root 'home#index'
  
  get "about_us", to: "home#about_us"
  get "contact_us", to: "home#contact_us"
  get "our_team", to: "home#our_team"
  get "categories", to: "home#categories"
  get "privacy_policy", to: "home#privacy_policy"

  resources :home do 
    collection do 
      get "about_us"
      get "contact_us"
      post "send_mail"
      get "our_team"
      get "categories"
      get "privacy_policy"
    end
  end

  # resources :sessions
  
  #sessions and sign up
  get "/users/login", to: "sessions#new", as: "login"
  get "/users/logout", to: "sessions#destroy", as: "logout"
  get "/users/resetpassword", to: "users#resetpassword", as: "resetpasswordform"
  post "/users/resetpassword", to: "users#resetpassword", as: "resetpassword"
  get "/users/resetp", to: "users#resetp"
  post "/users/updatepassword", to: "users#updatepassword", as: "updatepassword"
  get "/users/confirmation", to: "users#confirmation"
  get "/users/confirm", to: "users#confirm_user_email"
  get "/users/confirm_failure", to: "users#confirm_failure", as: "confirm_failure"
  get "/users/confirm_success", to: "users#confirm_success", as: "confirm_success"

  resources :users
  resources :sessions
  resources :jobs do 
    collection do 
      get "get_job_sub"
    end
    member do 
      get "bookmark"
    end
  end

  resources :resumes do
    member do
      get "bookmark"
    end
  end

  namespace :api do
    namespace :v1 do
      draw :api_routes      
    end
  end


  namespace :member do
    resources :profile do 
      collection do
        get "getselectdata"
      end
      member do 
        get "editresume"
      end
    end
    resources :jobs do 
      collection do
        get "get_job_sub"
        get "get_specialization"
        post "set_review_status"
        post "send_job_letter"
      end
      member do
        get "applications"
        post "application_info"
        get "fill_status"
        get "job_letter"
        delete "delete_job_application"
      end
    end
    resources :dashboards
  end

  namespace :admin do
    resources :dashboards do 
      collection do
        get "get_chart_data"
      end
    end
    resources :admin_profiles
    resources :employers
    resources :jobs do
      collection do
        get "get_job_subad"
        get "get_specializationad"
      end
    end
    resources :employees do
      collection do
        get "getselectdata"
        get "search"
      end
    end
    resources :settings do
      collection do 
        get "job_category_index"
        get "new_job_category"
        post "create_job_category"

        get "job_sub_category_index"
        get "new_job_sub_category"
        post "create_job_sub_category"

        get "ug_qualification_index"
        get "new_ug_qualification"
        post "create_ug_qualification"

        get "pg_qualification_index"
        get "new_pg_qualification"
        post "create_pg_qualification"

        get "phd_qualification_index"
        get "new_phd_qualification"
        post "create_phd_qualification"

        get "industry_index"
        get "new_industry"
        post "create_industry"

        get "country_index"
        get "new_country"
        post "create_country"

        get "location_index"
        get "new_location"
        post "create_location"

        get "designation_index"
        get "new_designation"
        post "create_designation"

      end
      member do
        get "edit_job_category"
        delete "delete_job_category"
        patch "update_job_category"

        get "edit_job_sub_category"
        delete "delete_job_sub_category"
        patch "update_job_sub_category"

        get "edit_ug_qualification"
        get "subjects"
        delete "delete_ug_qualification"
        patch "update_ug_qualification"

        get "edit_pg_qualification"
        get "specializations"
        delete "delete_pg_qualification"
        patch "update_pg_qualification"

        get "edit_phd_qualification"
        get "phd_specializations"
        delete "delete_phd_qualification"
        patch "update_phd_qualification"

        get "edit_industry"
        delete "delete_industry"
        patch "update_industry"

        get "edit_country"
        get "states"
        delete "delete_country"
        patch "update_country"

        get "edit_location"
        delete "delete_location"
        patch "update_location"

        get "edit_designation"
        delete "delete_designation"
        patch "update_designation"

      end
    end
  end

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < BackendController
  def index
    @latestposts = Job.all.desc(:created_at).limit(5)
    @todo = TodoList.new
    @todolist = TodoList.all.desc(:created_at)
    @user_array_with_ids = {}
    @user_array = []
    User.admins.where(:id.ne => current_user.id ).each do |usr|
      @user_array_with_ids[usr.name] = usr.id.to_s
      @user_array << usr.name
    end
  end

  def show
  end

  def create
    todo = TodoList.create(todoparams)
    render :partial => "todo", :object => todo
  end

  def destroy
    todo = TodoList.find(params[:id])
    todo.destroy
    render :json => {"success" => true}.to_json
  end

  def get_chart_data
    datasets = {}
    new_users = []
    jobs_posted = []
    position_filled = []    
    (1..31).each do |idx|
      dt = Time.now - idx.days
      temp = dt.strftime("%Y/%m/%d")
      temp = temp + " 00:00"
      sdt = Time.parse(temp)
      edt = sdt + 1.days
      users = User.where(:created_at.gt => sdt, :created_at.lt => edt).count
      new_users << [sdt.to_i * 1000, users]
      jobs = Job.where(:created_at.gt => sdt, :created_at.lt => edt).count
      jobs_posted << [sdt.to_i * 1000, jobs]
      jobs = Job.where(:created_at.gt => sdt, :created_at.lt => edt, :filled => true).count
      position_filled << [sdt.to_i * 1000, jobs]
    end

    datasets["new_users"] = {
      "label" => "New User Registered",
      "data" => new_users
    }
    datasets["jobs_posted"] = {
      "label" => "Jobs Posted",
      "data" => jobs_posted
    }
    datasets["position_filled"] = {
      "label" => "Position Filled",
      "data" => position_filled
    }
    render :json => datasets.to_json
  end

  private 

  def todoparams
    params.require(:todo_list).permit!
  end

end

app/controllers/member/candidates_controller.rb
class Member::CandidatesController < SkynetMemberController
	before_action :current_user, :except => [:show,:edit,:update,:destroy]

	def index
		@jobs = Job.desc(:created_at).page(params[:page]).per(15)
		#render :text => @jobs.to_json and return
	end

	def show
		@job = Job.find(params[:id])
		@job_category = JobCategory.find(:id => @job.job_category_id )
		@job_sub_category = JobSubCategory.find(:id => @job.job_sub_category_id )
		@company_name = EmployerProfile.find(:id => @job.employer_profile_id)
		@location = ImportantLocation.find(:id => @job.location_id)
		@job_designation = Designation.find(:id => @job.designation_id)
	end

end

app/controllers/member/dashboards_controller.rb
class Member::DashboardsController < SkynetMemberController
  
  def index
    if current_user.is_employee?
      @applications = current_user.profile.job_applications.desc(:created_at)
    elsif current_user.is_employer?
      @jobs = current_user.profile.jobs.desc(:created_at)
    end
 
    @bookmarks = Job.where(:bookmarked_ids.in => [current_user.id.to_s])
    @alerts = []
  end

end

app/controllers/member/jobs_controller.rb
class Member::JobsController < SkynetMemberController

  before_action :check_for_employer, :only => ["applications", "application_info", "new"]
 
  def index
    @jobs = Job.where(:employer_profile_id => current_user.profile.id).desc(:created_at)
  end
  
  def show
    
  end

  def new
    @job = Job.new
    @job_categories = JobCategory.all.asc(:name)
    @job_sub_categories = @job_categories.first.job_sub_categories.all.asc(:name)
    @ug_qualifications = UgQualification.all.asc(:name)
    @subjects = @ug_qualifications.first.subjects.asc(:name)
    @pg_qualifications = PgQualification.all.asc(:name)
    @specializations = @pg_qualifications.first.specializations.asc(:name)
    @phd_qualifications = PhdQualification.all.asc(:name)
    @phd_specializations = @phd_qualifications.first.phd_specializations.asc(:name) rescue [] 
    @tag_array = []
    @tag_array_with_ids = {}
    SkillTag.each do |tag|
      @tag_array << tag.name
      @tag_array_with_ids[tag.name] = tag.id.to_s 
    end
  end

  def create
    @job = Job.new(job_params)
    @job[:employer_profile_id] = current_user.profile 
    if @job.save
       redirect_to  member_dashboards_path
     else
       redirect_to  new_member_job_path
    end
  end

  def edit
    @job = Job.where(:uid => params[:id]).first rescue nil
    @job_categories = JobCategory.all.asc(:name)
    @job_sub_categories = @job_categories.first.job_sub_categories.all.asc(:name)

    @job_sub_category = JobSubCategory.where(:job_category_id =>@job[:job_category_id], :id => @job[:job_sub_category_id]).first
    
    @ug_qualifications = UgQualification.all.asc(:name)
    @subjects = @ug_qualifications.first.subjects.asc(:name)
    
    @pg_qualifications = PgQualification.all.asc(:name)
    @specializations = @pg_qualifications.first.specializations.asc(:name)
     
    @phd_qualifications = PhdQualification.all.asc(:name)
    @phd_specializations = @phd_qualifications.first.phd_specializations.asc(:name) rescue []
    @tag_array = []
    @tag_array_with_ids = {}
    SkillTag.each do |tag|
      @tag_array << tag.name
      @tag_array_with_ids[tag.name] = tag.id.to_s 
    end
  end

  def update
    job = Job.find(params[:id])
    if !job.nil?
      if job.update_attributes(job_params)
        if params[:page]
          redirect_to member_jobs_path(:page => params[:page])
        else
          redirect_to member_jobs_path
        end
      else
        redirect_to edit_member_job(job_params)
      end
    end
  end

  def destroy
    job = Job.find(params[:id])rescue nil
    job.destroy if !job.nil?
    redirect_to member_dashboards_path(:page => params[:page])
  end

  def get_job_sub
    jc = JobCategory.find(params[:job_category]) rescue nil
    if !jc.nil?
     @job_sub_categories = jc.job_sub_categories.all.asc(:name)
    end
    render :layout => false
  end

  def set_review_status
    application = JobApplication.find(params[:id])
    application.reviewed = true
    application.save
    render :json => {"success" => true}.to_json
  end

  def get_specialization
    case params[:type]
    when "ug"
      ug = UgQualification.find(params[:id])
      @objs = ug.subjects.asc(:name) rescue []
    when "pg"
      pg = PgQualification.find(params[:id])
      @objs = pg.specializations.asc(:name) rescue []
    when "phd"
      phd = PhdQualification.find(params[:id])
      @objs = phd.phd_specializations.asc(:name) rescue []
    end
    render :layout => false
  end

  def applications
    @job_skill_tags = @job.skill_tags

    case params[:status]
    when "0"
      @applications = @job.job_applications.new_applications
    when "1"
      @applications = @job.job_applications.interviewed
    when "2"
      @applications = @job.job_applications.offer_extended
    when "3"
      @applications = @job.job_applications.hired
    when "4"
      @applications = @job.job_applications.archived
    else
      @applications = @job.job_applications.new_applications
    end
    case params[:sort]
    when "date"
      @applications = @applications.order_by(:created_at => :desc)
    when "name"
      @applications = @applications.order_by(:"employee_profile.name" => :asc)
    when "rating"
      @applications = @applications.order_by(:rating => :desc)
    else
      @applications = @applications.order_by(:created_at => :desc)
    end
  end


  def fill_status
    job = Job.find(params[:id]) rescue nil
    if !job.nil?
      if params[:status] == "notfilled"
        job.filled = true
      elsif params[:status] == "filled"
        job.filled = false
      end
      job.save
      data = {"success" => true, "status" => job.filled}
    else
      data = {"success" => false}
    end
    render :json => data.to_json
  end


  def application_info
    ja = JobApplication.find(params[:application_id])
    ja.status = params[:status].present? ? params[:status] : ja.status
    ja.note = params[:note].present? ? params[:note] : ja.note
    ja.rating = params[:rating].present? ? params[:rating] : ja.rating
    ja.save
    render :json => {"success" => true, "rating" => ja.rating_for_stars, "status" => ja.get_status}.to_json
  end

  def delete_job_application
    ja = JobApplication.find(params[:id])
    job = ja.job
    ja.destroy
    redirect_to applications_member_job_path(job.uid)
  end

  def job_letter
    @job = Job.find(params[:id]) rescue nil
    @user = User.find(params[:user]) rescue nil
    render :layout => false
  end

  def send_job_letter
    user = User.find(params[:user]) rescue nil
    if !user.nil?
      user.send_job_letter(params[:msg], current_user)
      data = {"success" => true}
    else
      data = {"success" => false}
    end
    render :json => data.to_json
  end

  private

  def job_params
    p = params.require(:job).permit!
    if params["new_skill_tags"].present?
      params["new_skill_tags"].each do |nst|
        if nst.length < 41
          tag = SkillTag.create(:name => nst, :created_by => current_user.id)
          if p["skill_tag_ids"].present?
            p["skill_tag_ids"] << tag.id.to_s
          else
            p["skill_tag_ids"] = []
            p["skill_tag_ids"] << tag.id.to_s
          end
        end
      end
    end
    p  
  end
end

app/controllers/member/profile_controller.rb
class Member::ProfileController < SkynetMemberController

	before_action :check_for_username, :only => [:show, :edit, :editresume]

	def index 
	end

	def show
	end

	def editresume
		redirect_to edit_member_profile_path(current_user.user_name) if current_user.is_employer?
		@profile = current_user.profile
		@tag_array = []
		@tag_array_with_ids = {}
		SkillTag.each do |tag|
			@tag_array << tag.name
			@tag_array_with_ids[tag.name] = tag.id.to_s 
		end
	end

	def getselectdata
    if params[:type] == "qualification"
      case params[:value]
      when "0"
        @qualifications = UgQualification.all.asc(:name).collect{|qual| [qual.name, qual.id]}
      when "1"
        @qualifications = PgQualification.all.asc(:name).collect{|qual| [qual.name, qual.id]}
      when "2"
        @qualifications = PhdQualification.all.asc(:name).collect{|qual| [qual.name, qual.id]}
      end
    elsif params[:type] == "specialization"
      case params[:qualification_type]
      when "0"
        @qualifications = UgQualification.find(params[:value]).subjects.asc(:name).collect{|qual| [qual.name, qual.id]}
      when "1"
        @qualifications = PgQualification.find(params[:value]).specializations.asc(:name).collect{|qual| [qual.name, qual.id]}
      when "2"
        @qualifications = PhdQualification.find(params[:value]).phd_specializations.asc(:name).collect{|qual| [qual.name, qual.id]}
      end
    end
    render :layout => false
  end

	def edit
		@profile = current_user.profile
		@industries = Industry.all.asc(:name).collect{|industry| [industry.name, industry.id]}
		@states = Country.first.states.collect{|state| [state.name, state.id]}
		@locations = ImportantLocation.all.collect{|loc| [loc.name, loc.id]}
		@countries = Country.all.collect{|country| [country.name, country.id]}
    @job_categories = JobCategory.all.asc(:name)
    if current_user.is_employee?
      if @profile.job_category.nil? || @profile.job_category.empty?
        @job_sub_categories = @job_categories.first.job_sub_categories.all.asc(:name)
      else
        @job_sub_categories = @job_categories.find(@profile.job_category).job_sub_categories.all.asc(:name)
      end
    end
    
		if current_user.is_employee?
		 @ug_qualifications = UgQualification.all.asc(:name).collect{|qual| [qual.name, qual.id]}
   		 @ug_specializations = UgQualification.find(@ug_qualifications.first.last).subjects.all.asc(:name).collect{|sub| [sub.name, sub.id]}
		end
	end

	def update
		profile = current_user.profile
		if current_user.is_employer?
			profile.update_attributes(employer_profile_params)
		elsif current_user.is_employee?
			profile.update_attributes(employee_profile_params)
		end
		if !current_user.basic_registeration_complete
			current_user.basic_registeration_complete = true
			current_user.save
		end
		profile.save
    if current_user.is_employee? && profile.resume.url.nil?
      redirect_to editresume_member_profile_path(current_user.user_name)
    else
		  redirect_to member_dashboards_path
    end
	end

	private

	def check_for_username
		username = params[:id]
		redirect_to login_path if current_user.user_name != username
	end

	def employer_profile_params
		params.require(:employer_profile).permit!
	end

	def employee_profile_params
		p = params.require(:employee_profile).permit!
		if params["new_skill_tags"].present?
			params["new_skill_tags"].each do |nst|
        if nst.length < 41
  				tag = SkillTag.create(:name => nst, :created_by => current_user.id)
  				if p["skill_tag_ids"].present?
  					p["skill_tag_ids"] << tag.id.to_s
  				else
  					p["skill_tag_ids"] = []
  					p["skill_tag_ids"] << tag.id.to_s
  				end
        end
			end
		end
		p
	end
	
end

app/helpers/member/candidates_helper.rb
module Member::CandidatesHelper
end

app/helpers/member/ourteams_helper.rb
module Member::OurteamsHelper
end

app/views/member/dashboards/_application.html.erb
<tr>
	<td><a href="<%= job_path(application.job.uid) %>"><%= application.job.uid %></a></td>
	<td><%= Designation.find(application.job.designation_id).name rescue "" %></td>
	<td><%= application.job.employer_profile.company_name %></td>
	<td><%= application.job.get_locations.join(", ") %></td>
	<td><%= application.created_at.strftime("%d/%m/%Y") %></td>
	<td><%= application.review_status %></td>
	<td><%= application.job.get_job_type %></td>
	<td class="action">
		<a href="<%= job_path(application) %>" data-method="delete" data-confirm="Are you sure?" class="delete"><i class="fa fa-remove"></i> Delete</a>
	</td>
</tr>

app/views/member/dashboards/_bookmark.html.erb
<tr>
	<td><a href="<%= job_path(bookmark.uid) %>"><%= bookmark.uid %></a></td>
	<td><%= Designation.find(bookmark.designation_id).name rescue "" %></td>
	<td><%= bookmark.employer_profile.company_name %></td>
	<td><%= bookmark.get_locations.join(", ") %></td>
	<td><%= bookmark.get_job_type %></td>
	<td class="action">
		<a href="<%= bookmark_job_path(bookmark.id, :status => "no") %>" data-confirm="Are you sure?" class="delete"><i class="fa fa-remove"></i> Remove</a>
	</td>
</tr>

app/views/member/dashboards/_employee_index.html.erb
<div class="container">
	<div class="margin-bottom-20"></div>
	<div class="three columns side-menu">
		<h4>Important Links</h4>
		<ul class="side-menu">
			<li><i class="fa fa-eye" aria-hidden="true"></i><a href="<%= resume_path(current_user.uid) %>">View Profile</a></li>
			<li><i class="fa fa-user" aria-hidden="true"></i><a href="<%= edit_member_profile_path(current_user.user_name) %>"> Edit Profile</a></li>
			<li><i class="fa fa-pencil-square-o" aria-hidden="true"></i><a href="<%= editresume_member_profile_path(current_user.user_name) %>">Edit Resume</a></li>
		</ul>
	</div>
	<div class="thirteen columns">
		<!-- Tabs Navigation -->
		<ul class="tabs-nav">
			<li class="active"><a href="#applications">Job Applications</a></li>
			<li><a href="#bookmarks">Bookmarks</a></li>
			<!-- <li><a href="#alerts">Job Alerts</a></li> -->
		</ul>

		<!-- Tabs Content -->
		<div class="tabs-container">
			<div class="tab-content" id="applications">
				<% if !@applications.blank? %>
					<p class="margin-bottom-25">Your applied jobs are shown below</p>
					<table class="manage-table resumes responsive-table">
						<tr>
							<th><b>#</b> ID</th>
							<th><i class="fa fa-id-badge" aria-hidden="true"></i> Position</th>
							<th><i class="fa fa-building-o"></i> Company</th>
							<th><i class="fa fa-map-marker"></i> Location</th>
							<th><i class="fa fa-calendar-o"></i> Date</th>
							<th><i class="fa fa-check-square-o"></i> Status</th>
							<th><i class="fa fa-users"></i> Job Type</th>
							<th></th>
						</tr>
						<%= render :partial => "application", :collection => @applications %>
					</table>
				<% else %>
					<p class="margin-bottom-25">You haven't applied for any jobs yet.</p>
				<% end %>
			</div>

			<div class="tab-content" id="bookmarks">
				<% if !@bookmarks.blank? %>
					<p class="margin-bottom-25">Your bookmarked jobs are shown below</p>
					<table class="manage-table resumes responsive-table">
						<tr>
							<th><b>#</b> ID</th>
							<th><i class="fa fa-id-badge" aria-hidden="true"></i> Position</th>
							<th><i class="fa fa-building-o"></i> Company</th>
							<th><i class="fa fa-map-marker"></i> Location</th>
							<th><i class="fa fa-users"></i> Job Type</th>
							<th></th>
						</tr>
						<%= render :partial => "bookmark", :collection => @bookmarks %>
					</table>
				<% else %>
					<p class="margin-bottom-25">You haven't bookmarked any jobs yet.</p>
				<% end %>
			</div>

			<div class="tab-content" id="alerts">
			<% if !@alerts.blank? %>
				<p class="margin-bottom-25">Your job alerts are shown below.</p>
				<table class="manage-table resumes responsive-table">
					<tr>
						<th><i class="fa fa-file-text"></i> Alert Name</th>
						<th><i class="fa fa-calendar"></i> Date Created</th>
						<th><i class="fa fa-tags"></i> Keywords</th>
						<th><i class="fa fa-map-marker"></i> Location</th>
						<th><i class="fa fa-clock-o"></i> Frequency</th>
						<th><i class="fa fa-check-square-o"></i> Status</th>
						<th></th>
					</tr>
					<tr>
						<td class="alert-name">Looking for job</td>
						<td>September 30, 2015</td>
						<td class="keywords">Web Developer, PHP, HTML</td>
						<td>London</td>
						<td>Daily</td>
						<td>Enabled</td>
						<td class="action">
							<a href="#"><i class="fa fa-check-circle-o"></i> Show Results</a>
							<a href="#"><i class="fa fa-envelope"></i> Email</a>
							<a href="#"><i class="fa fa-pencil"></i> Edit</a>
							<a href="#"><i class="fa  fa-eye-slash"></i> Disable</a>
							<a href="#" class="delete"><i class="fa fa-remove"></i> Delete</a>
						</td>
					</tr>
				</table>
			<% else %>
				<p class="margin-bottom-25">You don't have any job alerts yet.</p>
			<% end %>
				<br>
				<a href="#small-dialog" class="popup-with-zoom-anim button">Add Alert</a>
				<div id="small-dialog" class="zoom-anim-dialog mfp-hide apply-popup">
					<div class="small-dialog-headline">
						<h2>Add Alert</h2>
					</div>

					<div class="small-dialog-content">
						<form action="#" method="get" >
							<input type="text" placeholder="Alert Name" value=""/>
							<input type="text" placeholder="Keyword" value=""/>
							<input type="text" placeholder="Location" value=""/>

							<!-- Select -->
							<select data-placeholder="Email Frequency" class="chosen-select-no-single">
								<option value="">Email Frequency</option>
								<option value="1">Daily</option>
								<option value="2">Weekly</option>
								<option value="3">Fortnightly</option>
							</select>

							<div class="clearfix"></div>
							<div class="margin-top-15"></div>

							<!-- Select -->
							<select data-placeholder="Job Type" class="chosen-select" multiple>
								<option value="1">Full-Time</option>
								<option value="2">Part-Time</option>
								<option value="3">Internship</option>
								<option value="4">Freelance</option>
								<option value="5">Temporary</option>
							</select>

							<div class="margin-top-20"></div>
							<div class="divider"></div>

							<button class="send">Save Alert</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/member/dashboards/_employer_index.html.erb
<p class="margin-bottom-25">Your job listings are shown in the table below.</p>

<table class="manage-table responsive-table">

	<tr>
		<th><i class="fa fa-file-text"></i> Title</th>
		<th><i class="fa fa-check-square-o"></i> Filled?</th>
		<th><i class="fa fa-calendar"></i> Date Posted</th>
		<th><i class="fa fa-user"></i> Applications</th>
		<th></th>
	</tr>
	<%= render :partial => "job", :collection => @jobs %>
</table>

<br>
<a href="<%= new_member_job_path %>" class="button">Add Job</a>

<% content_for :page_specific_js do %>
	<script type="text/javascript">
		$(".fill-status-btn").on("click",function(){
			var el = $(this),
					status = el.data("status");
			$.ajax({
				url : el.attr("href"),
				data : {"status" : status},
				dataType : "json"
			}).done(function(data){
				if(data.success){
					if(data.status){
						el.find("span").text("Mark not-filled");
						el.data("status", "filled");
						$(".fill-status-area").text("Filled");
					}else{
						el.find("span").text("Mark Filled");
						el.data("status", "notfilled");
						$(".fill-status-area").text("-");
					}
				}
			})
			return false;
		})
	</script>
<% end %>

app/views/member/dashboards/_job.html.erb
<tr>
	<% job_designation = Designation.find(:id => job.designation_id )rescue nil %>
	<td class="title"><a href="<%= job_path(job.uid) %>" target="_blank"><%= job_designation.name rescue "Not Applicable" %></a></td>
	<% if job.filled %>
		<td class="centered fill-status-area">Filled</td>
	<% else %>
		<td class="centered fill-status-area">-</td>
	<% end %>
	<td><%= job.created_at.strftime("%B %d %Y") %></td>
	<td class="centered"><a href="<%= applications_member_job_path(job.uid) %>" class="button <%= job.job_applications.count > 0 ? "" : "disable" %>">Show (<%= job.job_applications.count %>)</a></td>
	<td class="action">
		<!-- <a href="edit_member_job_path"><i class="fa fa-pencil"></i> Edit</a> -->
		<a href="<%= edit_member_job_path(job.uid, :page=>params[:page]) %>"><i class="fa fa-pencil"></i>Edit</a>
		<% if job.filled %>
			<a href="<%= fill_status_member_job_path(job.id) %>" data-status="filled" class="fill-status-btn"><i class="fa fa-check "></i> <span>Mark not-filled</span></a>
		<% else %>
			<a href="<%= fill_status_member_job_path(job.id) %>" data-status="notfilled" class="fill-status-btn"><i class="fa fa-check "></i> <span>Mark Filled</span></a>
		<% end %>
		<%= link_to member_job_path(:id => job.id) , :method => :delete, :data => {:confirm => "Are you sure?"} do %>
				<i class="fa fa-remove"></i> Delete
		<% end %>
		
	</td>
</tr>	

app/views/member/dashboards/index.html.erb
<%= csrf_meta_tags %>
<% content_for :page_specific_breadcrumb do %>
<!-- Titlebar
================================================== -->
<div id="titlebar" class="photo-bg" style="background-image: url(/assets/banner-home-04.jpg);">
    <div class="container">
        <div class="ten columns">
            <h3 style="color: #c8c8c8;">Welcome</h3>
            <h2><%= current_user.name %></h2>
        </div>
    </div>
</div>
<% end %>
<!-- Content
================================================== -->
<div class="container">
	<div class="seventeen columns">
		<% if current_user.is_employee? %>
			<%= render :partial => "employee_index" %>
		<% elsif current_user.is_employer? %>
			<%= render :partial => "employer_index" %>
		<% end %>
		<br>
	</div>
</div>

<script type="text/javascript">
	$(".disable").on("click",function(){
		return false;
	})
</script>