config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # site root

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/#{routes_name}.rb")))
  end

  root 'home#index'
  
  get "about_us", to: "home#about_us"
  get "contact_us", to: "home#contact_us"
  get "our_team", to: "home#our_team"
  get "categories", to: "home#categories"
  get "privacy_policy", to: "home#privacy_policy"

  resources :home do 
    collection do 
      get "about_us"
      get "contact_us"
      post "send_mail"
      get "our_team"
      get "categories"
      get "privacy_policy"
    end
  end

  # resources :sessions
  
  #sessions and sign up
  get "/users/login", to: "sessions#new", as: "login"
  get "/users/logout", to: "sessions#destroy", as: "logout"
  get "/users/resetpassword", to: "users#resetpassword", as: "resetpasswordform"
  post "/users/resetpassword", to: "users#resetpassword", as: "resetpassword"
  get "/users/resetp", to: "users#resetp"
  post "/users/updatepassword", to: "users#updatepassword", as: "updatepassword"
  get "/users/confirmation", to: "users#confirmation"
  get "/users/confirm", to: "users#confirm_user_email"
  get "/users/confirm_failure", to: "users#confirm_failure", as: "confirm_failure"
  get "/users/confirm_success", to: "users#confirm_success", as: "confirm_success"

  resources :users
  resources :sessions
  resources :jobs do 
    collection do 
      get "get_job_sub"
    end
    member do 
      get "bookmark"
    end
  end

  resources :resumes do
    member do
      get "bookmark"
    end
  end

  namespace :api do
    namespace :v1 do
      draw :api_routes      
    end
  end


  namespace :member do
    resources :profile do 
      collection do
        get "getselectdata"
      end
      member do 
        get "editresume"
      end
    end
    resources :jobs do 
      collection do
        get "get_job_sub"
        get "get_specialization"
        post "set_review_status"
        post "send_job_letter"
      end
      member do
        get "applications"
        post "application_info"
        get "fill_status"
        get "job_letter"
        delete "delete_job_application"
      end
    end
    resources :dashboards
  end

  namespace :admin do
    resources :dashboards do 
      collection do
        get "get_chart_data"
      end
    end
    resources :admin_profiles
    resources :employers
    resources :jobs do
      collection do
        get "get_job_subad"
        get "get_specializationad"
      end
    end
    resources :employees do
      collection do
        get "getselectdata"
        get "search"
      end
    end
    resources :settings do
      collection do 
        get "job_category_index"
        get "new_job_category"
        post "create_job_category"

        get "job_sub_category_index"
        get "new_job_sub_category"
        post "create_job_sub_category"

        get "ug_qualification_index"
        get "new_ug_qualification"
        post "create_ug_qualification"

        get "pg_qualification_index"
        get "new_pg_qualification"
        post "create_pg_qualification"

        get "phd_qualification_index"
        get "new_phd_qualification"
        post "create_phd_qualification"

        get "industry_index"
        get "new_industry"
        post "create_industry"

        get "country_index"
        get "new_country"
        post "create_country"

        get "location_index"
        get "new_location"
        post "create_location"

        get "designation_index"
        get "new_designation"
        post "create_designation"

      end
      member do
        get "edit_job_category"
        delete "delete_job_category"
        patch "update_job_category"

        get "edit_job_sub_category"
        delete "delete_job_sub_category"
        patch "update_job_sub_category"

        get "edit_ug_qualification"
        get "subjects"
        delete "delete_ug_qualification"
        patch "update_ug_qualification"

        get "edit_pg_qualification"
        get "specializations"
        delete "delete_pg_qualification"
        patch "update_pg_qualification"

        get "edit_phd_qualification"
        get "phd_specializations"
        delete "delete_phd_qualification"
        patch "update_phd_qualification"

        get "edit_industry"
        delete "delete_industry"
        patch "update_industry"

        get "edit_country"
        get "states"
        delete "delete_country"
        patch "update_country"

        get "edit_location"
        delete "delete_location"
        patch "update_location"

        get "edit_designation"
        delete "delete_designation"
        patch "update_designation"

      end
    end
  end

end

app/views/shared/_back_header.html.erb
<!--Header-part-->
<div id="header">
  <h1><a href="<%= root_url %>">Skynet Dashboard</a></h1>
</div>
<!--close-Header-part--> 

<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <li  class="dropdown" id="profile-messages" ><a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">Welcome <%= current_user.name %></span><b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="<%= edit_admin_admin_profile_path(current_user.user_name) %>"><i class="icon-user"></i> My Profile</a></li>
        <li class="divider"></li>
        <!-- <li><a href="#"><i class="icon-check"></i> My Tasks</a></li> -->
        <!-- <li class="divider"></li> -->
        <li><a href="<%= logout_url %>"><i class="icon-key"></i> Log Out</a></li>
      </ul>
    </li>
    <!-- <li class="dropdown" id="menu-messages"><a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important">5</span> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a class="sAdd" title="" href="#"><i class="icon-plus"></i> new message</a></li>
        <li class="divider"></li>
        <li><a class="sInbox" title="" href="#"><i class="icon-envelope"></i> inbox</a></li>
        <li class="divider"></li>
        <li><a class="sOutbox" title="" href="#"><i class="icon-arrow-up"></i> outbox</a></li>
        <li class="divider"></li>
        <li><a class="sTrash" title="" href="#"><i class="icon-trash"></i> trash</a></li>
      </ul>
    </li>
    <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li> -->
    <li class=""><a title="" href="<%= logout_url %>"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
  </ul>
</div>
<!--close-top-Header-menu-->
<!--start-top-serch-->
<div id="search">
 <!--  <input type="text" placeholder="Search here..."/>
  <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button> -->
  <div class="date">
    <%= Time.now.strftime("%a, %d %b %Y") %>
  </div>
</div>
<!--close-top-serch-->

app/views/shared/_back_sidebar.html.erb
<!--sidebar-menu-->
<div id="sidebar"><a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
  <ul>
    <li class="<%= put_active "dashboards" %>"><a href="<%= admin_dashboards_path %>"><i class="icon icon-dashboard"></i> <span>Dashboard</span></a> </li>
    <% if current_user.is_super_admin? %>
      <li class="<%= put_active "admin_profiles" %> submenu"> <a href="#" onclick="return false;"><i class="icon icon-user"></i><span>Admin Users</span><span class="label nocolor"><i class="icarets <%= put_caret_sign %>"></i></span></a> 
        <ul>
          <li class="<%= put_sub_active "index" %>"><a href="<%= admin_admin_profiles_path %>">List Admins</a></li>
          <li class="<%= put_sub_active "new" %>"><a href="<%= new_admin_admin_profile_path %>">Create New Admin</a></li>
        </ul>
      </li>
    <% end %>
     <li class="<%= put_active "employers" %> submenu"> <a href="#"><i class="icon icon-briefcase"></i> <span>Employers</span><span class="label nocolor"><i class="icarets <%= put_caret_sign %>"></i></span></a> 
      <ul>
        <li class="<%= put_sub_active "index" %>"><a href="<%= admin_employers_path %>">List Employers</a></li>
        <li class="<%= put_sub_active "new" %>"><a href="<%= new_admin_employer_path %>">Create New Employer</a></li>
        <li class="<%= put_sub_active %>"><a href="#">Manpower Requirement</a></li>
      </ul>
    </li>
    <li class="<%= put_active "employees" %> submenu"> <a href="#"><i class="icon icon-group"></i> <span>Employees</span><span class="label nocolor"><i class="icarets <%= put_caret_sign %>"></i></span></a> 
      <ul>
        <li class="<%= put_sub_active "search" %>"><a href="<%= search_admin_employees_path %>">Search Employees</a></li>
        <li class="<%= put_sub_active "index" %>"><a href="<%= admin_employees_path %>">List Employees</a></li>
        <li class="<%= put_sub_active "new" %>"><a href="<%= new_admin_employee_path %>">Create New Employee</a></li>
      </ul>
    </li>
    <li class="<%= put_active "jobs" %> submenu"> <a href="#"><i class="icon icon-certificate"></i> <span>Jobs</span><span class="label nocolor"><i class="icarets <%= put_caret_sign %>"></i></span></a> 
      <ul>
       <li class="<%= put_sub_active "index" %>"><a href="<%= admin_jobs_path %>">List Jobs</a></li>
        <li class="<%= put_sub_active "new" %>"><a href="<%=  new_admin_job_path %>">Post New Job</a></li>
        <li class="<%= put_sub_active %>"><a href="#">Expired Jobs</a></li>
      </ul>
    </li>
    <% if current_user.is_super_admin? %>
      <li class="<%= put_active "settings" %> submenu"> <a href="#"><i class="icon icon-cogs"></i> <span>Settings</span><span class="label nocolor"><i class="icarets <%= put_caret_sign %>"></i></span></a> 
        <ul>
          <li class="<%= put_sub_active "job_category_index" %>"><a href="<%= job_category_index_admin_settings_path %>">Job Category</a></li>
          <li class="<%= put_sub_active "job_sub_category_index" %>"><a href="<%= job_sub_category_index_admin_settings_path %>">Job Sub Category</a></li>
          <li class="<%= put_sub_active "ug_qualification_index" %>"><a href="<%= ug_qualification_index_admin_settings_path %>">UG Qualification</a></li>
          <li class="<%= put_sub_active "pg_qualification_index" %>"><a href="<%= pg_qualification_index_admin_settings_path %>">PG Quaification</a></li>
          <li class="<%= put_sub_active "phd_qualification_index" %>"><a href="<%= phd_qualification_index_admin_settings_path %>">PHD Qualification</a></li>
          <li class="<%= put_sub_active "industry_index" %>"><a href="<%= industry_index_admin_settings_path %>">Industry List</a></li>
          <li class="<%= put_sub_active "country_index" %>"><a href="<%= country_index_admin_settings_path %>">Country</a></li>
          <li class="<%= put_sub_active "location_index" %>"><a href="<%= location_index_admin_settings_path %>">Location</a></li>
          <li class="<%= put_sub_active "designation_index" %>"><a href="<%= designation_index_admin_settings_path %>">Designation</a></li>
        </ul>
      </li>
    <% end %>
    <li class="<%= put_active %> submenu"> <a href="#"><i class="icon icon-credit-card"></i> <span>Payroll</span><span class="label nocolor"><i class="icarets <%= put_caret_sign %>"></i></span></a> 
      <ul>
        <li class="<%= put_sub_active %>"><a href="#">Company Master</a></li>
        <li class="<%= put_sub_active %>"><a href="#">Candidate Master</a></li>
      </ul>
    </li>
     <li class="<%= put_active %> submenu"> <a href="#"><i class="icon icon-road"></i> <span>Walk-In Zone</span><span class="label nocolor"><i class="icarets <%= put_caret_sign %>"></i></span></a> 
      <ul>
        <li class="<%= put_sub_active %>"><a href="#">Add New</a></li>
      </ul>
    </li>
  
    <!-- <li class="content"> <span>Monthly Bandwidth Transfer</span>
      <div class="progress progress-mini progress-danger active progress-striped">
        <div style="width: 77%;" class="bar"></div>
      </div>
      <span class="percent">77%</span>
      <div class="stat">21419.94 / 14000 MB</div>
    </li>
    <li class="content"> <span>Disk Space Usage</span>
      <div class="progress progress-mini active progress-striped">
        <div style="width: 87%;" class="bar"></div>
      </div>
      <span class="percent">87%</span>
      <div class="stat">604.44 / 4000 MB</div>
    </li> -->
  </ul>
</div>
<!--sidebar-menu-->

app/views/shared/_datepicker.html.erb
<% content_for :page_specific_css do %>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" type="text/css" href="/assets/datepicker/jquery-ui.min.css">
	<link rel="stylesheet" type="text/css" href="/assets/datepicker/jquery-ui.structure.css">
	<link rel="stylesheet" type="text/css" href="/assets/datepicker/jquery-ui.theme.min.css">
<% end %>

<% content_for :page_specific_js do %>
	<script src="/assets/datepicker/jquery-ui.min.js"></script>
<% end %>

app/views/shared/_front_footer.html.erb
<!-- Footer
================================================== -->
<% if !current_page?(root_url) %>
		<div class="margin-top-15"></div>
<% end %>
<div id="footer">
		<!-- Main -->
	<div class="container">
		<div class="seven columns">
			<h4>Skynet Placements</h4>
			<p>Skynet Placements is one of the leading Recruitment, HR & IR Labor laws Consulting Company Since 2003 with an objective to provide comprehensive HR Services to all over the India as well for the International Recruitment.</p>
			<% if current_user.nil? %>
					<a href="<%= login_path %>" class="button">Get Started</a>
			<% end %>
		</div>

		<div class="three columns">
			<h4>Company</h4>
			<ul class="footer-links">
					<li><a href="<%= about_us_path %>">About Us</a></li>
					<li><a href="<%= contact_us_path %>">Contact Us</a></li>
					<li><a href="<%= our_team_path %>">Our Team</a></li>
					<li><a href="#">Terms of Service</a></li>
					<li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
			</ul>
		</div>

		<div class="three columns" style="width:325px;">
			<h4>Contact</h4>
			<div>
				<% if current_user.nil? || current_user.is_employer? || current_user.is_admin? %>
					<p>
						For Employers:<br />
						Email: <a href="mailto:customercare@skynetplacements.com"> customercare@skynetplacements.com</a><br />
						Tel: <a href="tel:91-9512266262"> +91-9512266262</a>
					</p>
				<% end %>
				<% if current_user.nil? || current_user.is_employee? || current_user.is_admin? %>
					<p>
						For Employees:<br />
						Email: <a href="mailto:reach@skynetplacements.com">reach@skynetplacements.com</a><br />
						Tel: <a href="tel:91-9512166262">+91-9512166262</a>
					</p>
				<% end %>
			</div>
		</div>

		
			
		 <!--  <div class="three columns">
					<h4>Press</h4>
					<ul class="footer-links">
							<li><a href="#">In the News</a></li>
							<li><a href="#">Press Releases</a></li>
							<li><a href="#">Awards</a></li>
							<li><a href="#">Testimonials</a></li>
							<li><a href="#">Timeline</a></li>
					</ul>
			</div>    -->   

		 <!--  <div class="three columns">
					<h4>Browse</h4>
					<ul class="footer-links">
							<li><a href="#">Freelancers by Category</a></li>
							<li><a href="#">Freelancers in USA</a></li>
							<li><a href="#">Freelancers in UK</a></li>
							<li><a href="#">Freelancers in Canada</a></li>
							<li><a href="#">Freelancers in Australia</a></li>
							<li><a href="#">Find Jobs</a></li>

					</ul>
			</div> -->

	</div>

		<!-- Bottom -->
	<div class="container">
		<div class="footer-bottom">
			<div class="sixteen columns">
				<h4>Follow Us</h4>
				<ul class="social-icons">
					<li><a class="facebook" href="https://www.facebook.com/Skynet-Placements-126794617416629/" target="_blank"><i class="icon-facebook"></i></a></li>
					<li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
					<li><a class="gplus" href="#"><i class="icon-gplus"></i></a></li>
					<li><a class="linkedin" href="https://www.linkedin.com/in/skynet-placements-76849569/" target="_blank"><i class="icon-linkedin"></i></a></li>
				</ul>
				<div class="copyrights">©  Copyright 2017 by <a href="#">Skynet Placements</a>. All Rights Reserved.</div>
			</div>
		</div>
	</div>

</div>

app/views/shared/_front_header.html.erb
<!-- Header
================================================== -->
<header class=" sticky-header full-width <%= current_page?(root_url) ? "transparent" : "" %>">
  <div class="container">
    <div class="sixteen columns">
    
      <!-- Logo -->
      <div id="logo">
          <h1><a href="/"><img src="<%= current_page?(root_url) ? "/assets/logo.png" : "/assets/logo2.png" %>" alt="Sky net" /></a></h1>
      </div>

      <!-- Menu -->
      <nav id="navigation" class="menu">
        <ul id="responsive">

          <li><a href="<%= root_url %>" <%= put_front_active(["home"]) %>>Home</a>
              <ul>
                  <li><a href="<%= about_us_path %>" <%= put_front_active(["home/about_us"]) %>>About Us</a></li>
                  <li><a href="<%= our_team_path %>">Our Team</a></li>
                  <li><a href="#">Services</a></li>
                  <li><a href="#">Careers</a></li>
                  <li><a href="<%= contact_us_path %>" <%= put_front_active(["home/contact_us"]) %>>Contact Us</a></li>
              </ul>
          </li>

          <!-- <li><a href="#">Pages</a>
              <ul>
                  <li><a href="job-page.html">Job Page</a></li>
                  <li><a href="job-page-alt.html">Job Page Alternative</a></li>
                  <li><a href="resume-page.html">Resume Page</a></li>
                  <li><a href="shortcodes.html">Shortcodes</a></li>
                  <li><a href="icons.html">Icons</a></li>
                  <li><a href="pricing-tables.html">Pricing Tables</a></li>
                  <li><a href="contact.html">Contact</a></li>
              </ul>
          </li> -->
          <% if (!current_user.is_employer? rescue true) %>
            <li><a href="#" <%= put_front_active(["member/candidates"]) %> onclick="return false;">For Candidates</a>
                <ul>
                    <li><a href="<%= jobs_path %>">Browse Jobs</a></li>
                    <li><a href="<%= categories_path %>">Browse Categories</a></li>
                    <% if (current_user.is_employee? rescue false) %>
                      <li><a href="<%= member_dashboards_path + "#alerts" %>">Job Alerts</a></li>
                    <% end %>
                </ul>
            </li>
          <% end %>
          <% if (!current_user.is_employee? rescue true) %>
            <li><a href="#" <%= put_front_active(["member/jobs"]) %> onclick="return false;" >For Employers</a>
                <ul>
                    <% if (current_user.is_employer? rescue false) %>
                        <li><a href="<%= new_member_job_path %>">Add Job</a></li>
                        <li><a href="<%= member_dashboards_path %>">Manage Jobs</a></li>
                    <% end %>
                    <li><a href="<%= resumes_path %>">Browse Resumes</a></li>
                </ul>
            </li>
          <% end %>
          <!-- <li><a href="blog.html">Blog</a></li> -->
        </ul>

        <ul class="float-right">
            <% if current_user.nil? %>
                <li><a href="/users/login#tab2"><i class="fa fa-user"></i> Sign Up</a></li>
                <li><a href="/users/login"><i class="fa fa-lock"></i> Log In</a></li>
            <% else %>
                <li><a href="#"><img src="<%= !current_user.avatar.nil? && !current_user.avatar.url.nil? ? current_user.avatar.thumb.url : "http://api.adorable.io/avatar/200/#{current_user.user_name}" %>" class="header-avatar" /><%= current_user.name %></a>
                    <ul>
                        <% if current_user.is_employee? or current_user.is_employer? %>
                          <li>
                            <a href="<%= member_dashboards_path %>">
                                <i class="fa fa-dashboard"></i>
                                Dashboard
                            </a>
                          </li>
                        <li>
                            <a href="<%= edit_member_profile_path(current_user.user_name) %>">
                                <i class="fa fa-user"></i>
                                Edit Profile
                            </a>
                        </li>
                        <% end %>
                        <% if current_user.is_employee? %>
                            <li>
                                <a href="<%= editresume_member_profile_path(current_user.user_name) %>">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                    Edit Resume
                                </a>
                            </li>
                        <% end %>
                        <% if current_user.is_admin? %>
                            <li>
                                <a href="<%= admin_dashboards_path %>">
                                    <i class="fa fa-tachometer" aria-hidden="true"></i>
                                    Dashboard
                                </a>
                            </li>
                        <% end %>

                        <li>
                            <a href="<%= logout_url %>">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </li>
            <% end %>
        </ul>

      </nav>

      <!-- Navigation -->
      <div id="mobile-navigation">
          <a href="#menu" class="menu-trigger"><i class="fa fa-reorder"></i> Menu</a>
      </div>

    </div>
  </div>
</header>
<div class="clearfix"></div>

app/views/shared/_metas.html.erb
<!-- Basic Page Needs
================================================== -->
<meta charset="utf-8">
<title>Skynet Placements</title>

<!-- Mobile Specific Metas
================================================== -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="shortcut icon" href="/assets/favicon.png" type="image/x-icon">

<!-- CSS
================================================== -->
<!-- <link rel="stylesheet" href="/assets/style.css">
<link rel="stylesheet" href="/assets/colors/green.css" id="colors"> -->
<!-- Latest compiled and minified CSS -->
<%= stylesheet_link_tag "style.css" %>
<%= stylesheet_link_tag "colors/green.css" %>
<%= yield :page_specific_css %>
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/shared/_tagit.html.erb
<% content_for :page_specific_css do %>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href="/assets/tagit/jquery.tagit.css">
<% end %>

<% content_for :page_specific_js do %>
	<script src="/assets/tagit/jquery-ui.min.js"></script>
	<script src="/assets/tagit/tag-it.min.js"></script>
<% end %>