config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # site root

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/#{routes_name}.rb")))
  end

  root 'home#index'
  
  get "about_us", to: "home#about_us"
  get "contact_us", to: "home#contact_us"
  get "our_team", to: "home#our_team"
  get "categories", to: "home#categories"
  get "privacy_policy", to: "home#privacy_policy"

  resources :home do 
    collection do 
      get "about_us"
      get "contact_us"
      post "send_mail"
      get "our_team"
      get "categories"
      get "privacy_policy"
    end
  end

  # resources :sessions
  
  #sessions and sign up
  get "/users/login", to: "sessions#new", as: "login"
  get "/users/logout", to: "sessions#destroy", as: "logout"
  get "/users/resetpassword", to: "users#resetpassword", as: "resetpasswordform"
  post "/users/resetpassword", to: "users#resetpassword", as: "resetpassword"
  get "/users/resetp", to: "users#resetp"
  post "/users/updatepassword", to: "users#updatepassword", as: "updatepassword"
  get "/users/confirmation", to: "users#confirmation"
  get "/users/confirm", to: "users#confirm_user_email"
  get "/users/confirm_failure", to: "users#confirm_failure", as: "confirm_failure"
  get "/users/confirm_success", to: "users#confirm_success", as: "confirm_success"

  resources :users
  resources :sessions
  resources :jobs do 
    collection do 
      get "get_job_sub"
    end
    member do 
      get "bookmark"
    end
  end

  resources :resumes do
    member do
      get "bookmark"
    end
  end

  namespace :api do
    namespace :v1 do
      draw :api_routes      
    end
  end


  namespace :member do
    resources :profile do 
      collection do
        get "getselectdata"
      end
      member do 
        get "editresume"
      end
    end
    resources :jobs do 
      collection do
        get "get_job_sub"
        get "get_specialization"
        post "set_review_status"
        post "send_job_letter"
      end
      member do
        get "applications"
        post "application_info"
        get "fill_status"
        get "job_letter"
        delete "delete_job_application"
      end
    end
    resources :dashboards
  end

  namespace :admin do
    resources :dashboards do 
      collection do
        get "get_chart_data"
      end
    end
    resources :admin_profiles
    resources :employers
    resources :jobs do
      collection do
        get "get_job_subad"
        get "get_specializationad"
      end
    end
    resources :employees do
      collection do
        get "getselectdata"
        get "search"
      end
    end
    resources :settings do
      collection do 
        get "job_category_index"
        get "new_job_category"
        post "create_job_category"

        get "job_sub_category_index"
        get "new_job_sub_category"
        post "create_job_sub_category"

        get "ug_qualification_index"
        get "new_ug_qualification"
        post "create_ug_qualification"

        get "pg_qualification_index"
        get "new_pg_qualification"
        post "create_pg_qualification"

        get "phd_qualification_index"
        get "new_phd_qualification"
        post "create_phd_qualification"

        get "industry_index"
        get "new_industry"
        post "create_industry"

        get "country_index"
        get "new_country"
        post "create_country"

        get "location_index"
        get "new_location"
        post "create_location"

        get "designation_index"
        get "new_designation"
        post "create_designation"

      end
      member do
        get "edit_job_category"
        delete "delete_job_category"
        patch "update_job_category"

        get "edit_job_sub_category"
        delete "delete_job_sub_category"
        patch "update_job_sub_category"

        get "edit_ug_qualification"
        get "subjects"
        delete "delete_ug_qualification"
        patch "update_ug_qualification"

        get "edit_pg_qualification"
        get "specializations"
        delete "delete_pg_qualification"
        patch "update_pg_qualification"

        get "edit_phd_qualification"
        get "phd_specializations"
        delete "delete_phd_qualification"
        patch "update_phd_qualification"

        get "edit_industry"
        delete "delete_industry"
        patch "update_industry"

        get "edit_country"
        get "states"
        delete "delete_country"
        patch "update_country"

        get "edit_location"
        delete "delete_location"
        patch "update_location"

        get "edit_designation"
        delete "delete_designation"
        patch "update_designation"

      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < FrontendController
  
  def index
    @recent_jobs = Job.desc(:created_at).limit(6)
    @popular_categories = JobCategory.homepage_enabled
    @spotlight_jobs = Job.not_filled.spotlight_jobs
    if @spotlight_jobs.count == 0
      @spotlight_jobs = Job.not_filled.where(:max_salary_int.gt => 5).limit(5).desc(:max_salary_int)
    end
  end

  def about_us
  end

  def contact_us
  end

  def our_team
  end

  def privacy_policy
  end

  def send_mail
    render :text => params.to_json and return
  end

  def categories
    @categories = JobCategory.all.asc(:name)
  end

end

app/views/home/_banner.html.erb
<!-- Banner
================================================== -->
<div id="banner" class="with-transparent-header parallax background" style="background-image: url(/assets/banner-home-07.jpg)" data-img-width="2000" data-img-height="1330" data-diff="300">
	<div class="container">
		<div class="sixteen columns">
			
			<div class="search-container">

				<!-- Form -->
				<div class="box-search" <%= current_user.nil? || current_user.is_employee? ? "style=width:100%;" : "" %>>
					<h2>Find job</h2>
					<form action="<%= jobs_path %>" method="get"><input type="text" name="keywords" class="ico-01" placeholder="job title, keywords or company name; seperate keywords with (,)" value=""/></form>
				</div>
				
				<% if !current_user.nil? && !current_user.is_employee? %>
					<div class="box-search">
						<h2>Find employee</h2>
						<form action="<%= resumes_path %>" method="get"><input name="keywords" type="text" class="ico-03" placeholder="designation, keywords etc; Seperate keywords with a comma (,)" value=""/></form>
					</div>
				<% end %>
				<button><i class="fa fa-search"></i></button>

				
				<!-- Announce -->
				<div class="announce">
					We’ve over <strong><%= Job.count %></strong> jobs and <strong><%= EmployeeProfile.count %></strong> candidates for you!
				</div>

			</div>

		</div>
	</div>
</div>

app/views/home/_category.html.erb
<div class="container">
  <div class="four columns"><h5><a href="<%= jobs_path(:category => category.id) %>" style="color:black;"><%= category.name %></a></h5></div>
  <% total = category.job_sub_categories.count 
  	 percolumn = (total.to_f / 3.0).ceil %>
  <% idx = 0 %>
  <% category.job_sub_categories.each_with_index do |cat, i| %>
  	<% if idx == 0 %>
  		<div class="four columns">
  			<ul>
  	<% end %>
  				<li><a href="<%= jobs_path(:sub_category => cat.id) %>"><%= cat.name %></a></li>
  	<% idx = idx + 1 %>
  	<% if idx == percolumn || i == (total - 1) %>
  			</ul>
  		</div>
  		<% idx = 0 %>
  	<% end %>
  <% end %>
</div>
<div class="margin-bottom-50"></div>

app/views/home/_recent_job.html.erb
<li class="highlighted">
	<a href="<%= job_path(recent_job.uid) %>">
	<% if recent_job.is_premium? && current_user.is_premium? %>
		<img src="<%= recent_job.employer_profile.get_avatar %>" alt="">
	<% elsif !recent_job.is_premium? %>
		<% if recent_job.employer_profile.nil? || recent_job.employer_profile.avatar.url.nil? %>
			<img src="/assets/job-list-logo-01.png" alt="">
		<% else %>
			<img src="<%= recent_job.employer_profile.avatar.url %>" alt="">
		<% end %>
	<% else %>
		<img src="/assets/job-list-logo-01.png" alt="">
	<% end %>
		<div class="job-list-content">
			<h4><%= recent_job.job_category.name %> / <%= recent_job.job_sub_category.name %> <span class="<%= recent_job.get_job_type.downcase %>"><%= recent_job.get_job_type %></span></h4>
			<div class="job-icons">
				<span><i class="fa fa-briefcase"></i> 
					<% if recent_job.is_premium? && current_user.is_premium? %>
						<%= recent_job.employer_profile.company_name rescue "" %>
					<% elsif !recent_job.is_premium? %>
						<%= recent_job.employer_profile.company_name rescue "" %>
					<% else %>
						Premium job posting
					<% end %>
				</span>
				<span><i class="fa fa-map-marker"></i> <%= recent_job.get_locations.join(", ") %></span>
				<% if recent_job.display_salary && !recent_job.salary.blank? %>
					<span><i class="fa fa-inr"></i> <%= recent_job.salary.sub(",",".") %> Lacs / Year</span>
				<% end %>
			</div>
		</div>
	</a>
	<div class="clearfix"></div>
</li>

app/views/home/_spotlight.html.erb
<li>
	<div class="job-spotlight">
		<a href="#"><h4><%= spotlight.job_category.name %>: <%= spotlight.job_sub_category.name %><span class="<%= spotlight.get_job_type.downcase %>"><%= spotlight.get_job_type.downcase %></span></h4></a>
		<span><i class="fa fa-briefcase"></i>
			<% if spotlight.is_premium? && current_user.is_premium? %>
				<%= spotlight.employer_profile.company_name %>
			<% elsif !spotlight.is_premium? %>
				<%= spotlight.employer_profile.company_name %>
			<% else %>
				Premium job posting
			<% end %>
		</span>
		<span><i class="fa fa-map-marker"></i> <%= spotlight.get_locations.join(", ") %></span>
		<% if spotlight.display_salary %>
			<span><i class="fa fa-money"></i> <%= spotlight.get_salary_in_words %></span>
		<% end %>
		<% html = strip_tags(spotlight.job_description) %>
		<p>
			<%= html[0..150] %>
			<% if html.length > 150 %>
				...
			<% end %>
		</p>
		<a href="<%= job_path(spotlight.uid) %>" class="button">Apply For This Job</a>
	</div>
</li>

app/views/home/about_us.html.erb
<% content_for :page_specific_breadcrumb do %>
<!-- Titlebar
================================================== -->
<div id="titlebar" class="photo-bg" style="background-image: url(assets/banner-home-05.jpg);">
	<div class="container">

		<div class="sixteen columns">
			<h2>About Us</h2>
			<nav id="breadcrumbs">
				<ul>
					<li>You are here:</li>
					<li><a href="<%= root_url %>">Home</a></li>
					<li>About Us</li>
				</ul>
			</nav>
		</div>

	</div>
</div>
<% end %>
<!-- Container -->
<div class="container">
    <div class="sixteen columns">

        <h3 class="margin-bottom-20">Company Introduction-</h3>

    </div>
</div>
<!-- Container / End -->
<div class="container">
    <div class="sixteen columns">
        <p>Skynet Placements is one of the leading Recruitment, HR &amp; IR Labor laws Consulting Company Since 2003 with an objective to provide comprehensive HR Services to all over the India as well for the International Recruitment.</p>

				<p>Skynet Placements provide Contract Staffing &amp; end-to-end manpower recruitment solutions right from sourcing the cvs till the candidates join the organization.</p>

				<p>The establishment is headed by Mr. Rahul Sood who has done MSW &amp; IRPM   from Faculty of Social work &amp; LLB from Faculty of Law (MSU) along with versatile industrial experience in the field of HR &amp; IR.</p>

				<p>We have introduced with our latest service which includes Training &amp; Development which we are imparting towards the industrial area including the Top – Level management, Middle Level Management &amp; Shop – Floor Level Management.</p>
				<p>We are one of the leading Placement and Recruitment Consulting Company with an objective to Recruit Quality Employees that can be selected in order to help the organization to achieve its goals and objectives.</p>

				<p>Our endeavour is to recruit high calibre professionals across all functional areas. Our Company maintains a very strong and premium data bank of candidates.</p>

				<p>We as a Recruitment consultant act as a link between the employers and the job seekers and ensure the placement of right candidate at the right place at the right time. Using and following the right recruitment processes which can facilitate the selection of the best candidates for the organization.</p>
    </div>
</div>
<!-- Container -->
<div class="container  margin-top-20">
    <div class="sixteen columns">

        <h3 class="margin-bottom-10">OUR RECRUITMENT METHODLOGY--</h3>

    </div>
</div>
<!-- Container / End -->
<div class="container margin-bottom-50">
    <div class="sixteen columns">
    <ol class="about-us-points">
    	<li>
    		The Client's Needs Assessment, We try to get maximum possible details after lot of probing in all areas like skill sets required in our Resource requirement form, client's culture, industry requirements and performance expectations.
    	</li>
    	<li>
    		Position Specification After carefully assessing the client's needs, we then prepare a position specification to confirm the details and initiate the search plan.
    	</li>
    	<li>
    		Sourcing Strategy depending upon the requirement we decide our sourcing options &amp; if required go an extra mile get the candidates as per the requirement specifications of the client.</li>
    	<li>
    		Candidate Interviews and Evaluation We interview candidates, matching their strengths and capabilities against the position specifications at every step. Only the candidate’s best suited to the position are presented for client interviews.
    	</li>
    	<li>
    		Confidential references are also conducted to validate recommendations
    	</li>
    	<li>
    		Client's Final Selection. Once the client makes a final selection, the last stage involves offer negotiation to ensure an acceptance decision and lives through the joining processes.
    	</li>
    </ol>
    </div>
</div>

app/views/home/categories.html.erb
<% content_for :page_specific_breadcrumb do %>
<!-- Titlebar
================================================== -->
<div id="titlebar" class="photo-bg" style="background-image: url(assets/all-categories-photo.jpg);">
    <div class="container">
        <div class="ten columns">
            <h2>All Categories</h2>
        </div>
        <% if current_user.nil? || current_user.is_employer? %>
        <div class="six columns">
            <a href="<%= new_member_job_path %>" class="button">Post a Job, It’s Free!</a>
        </div>
        <% end %>
    </div>
</div>
<% end %>
<!-- Content
================================================== -->
<div id="categories">
  <!-- Categories Group -->
  <div class="categories-group">
    <%= render :partial => "category", :collection => @categories %>
  </div>
</div>

app/views/home/contact_us.html.erb
<% content_for :page_specific_breadcrumb do %>
<!-- Titlebar
================================================== -->
<div id="titlebar" class="photo-bg" style="background-image: url(assets/contact_us.png);">
    <div class="container">

        <div class="sixteen columns">
            <h2>Contact Us</h2>
            <nav id="breadcrumbs">
                <ul>
                    <li>You are here:</li>
                    <li><a href="<%= root_url %>">Home</a></li>
                    <li>Contact Us</li>
                </ul>
            </nav>
        </div>

    </div>
</div>
<% end %>
<!-- Container -->
<div class="container">
    <div class="sixteen columns">

        <h3 class="margin-bottom-20">Our Office</h3>

        <!-- Google Maps -->
        <section class="google-map-container">
            <div id="googlemaps" class="google-map google-map-full">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1845.491945935166!2d73.16752778812237!3d22.316448950163572!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x1ae597234267cf12!2sAtlantis+Building!5e0!3m2!1sen!2s!4v1503554894952" width="1180" height="250" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </section>
        <!-- Google Maps / End -->

    </div>
</div>
<!-- Container / End -->

<!-- Container -->
<div class="container">

<div class="eleven columns">

    <h3 class="margin-bottom-15">Contact Form</h3>
    
        <!-- Contact Form -->
        <section id="contact" class="padding-right">

            <!-- Success Message -->
            <mark id="message"></mark>

            <%= form_for send_mail_home_index_path, :url => { :action => "send_mail" }, :html => { :method => :post } do |f| %>
                <fieldset>
                    <div>
                        <%= f.label :name, "Name" %>
                        <%= f.text_field :name, :class => "" %>
                    </div>

                    <div>
                       <%= f.label :email do %>Email: <span>*</span><% end %>
                       <%= f.text_field :email, :required => true, :pattern => "^[A-Za-z0-9](([_\.\-]?[a-zA-Z0-9]+)*)@([A-Za-z0-9]+)(([\.\-]?[a-zA-Z0-9]+)*)\.([A-Za-z]{2,})$" %>
                    </div>

                    <div>
                        <%= f.label :message do %>Message: <span>*</span><% end %>
                        <%= f.text_area :comment, :required => true %>
                    </div>

                </fieldset>

                <div id="result"></div>
                <%= f.submit "Send Message", :class => "submit" %>
                <div class="clearfix"></div>
                <div class="margin-bottom-40"></div>
            <% end %>

        </section>

</div>
<!-- Container / End -->

<!-- Sidebar
================================================== -->
<div class="five columns">

    <!-- Information -->
    <h3 class="margin-bottom-10">Information</h3>
    <div class="widget-box">
        <p>SKYNET PLACEMENTS </p>

        <ul class="contact-informations">
            <li>Rahul Sood</li>
            <li>302 ATLANTIS,  </li>
            <li>Opp Vadodara Central, </li>
            <li>Genda Circle, Vadodara - 390023, </li>
            <li>Gujarat, INDIA </li>
        </ul>

        <ul class="contact-informations second" style="width:300px;">
          <% if current_user.nil? || current_user.is_employer? || current_user.is_admin? %>
              <li>For Employers:</li>
              <li><i class="fa fa-phone"></i> <p>+91-6353334677</p></li>
              <li><i class="fa fa-envelope"></i> <p>customercare@skynetplacements.com</p></li>
          <% end %>
          <% if current_user.nil? || current_user.is_employee? || current_user.is_admin? %>
              <li>For Employees:</li>
              <li><i class="fa fa-phone"></i> <p>+91-6353334677</p></li>
              <li><i class="fa fa-envelope"></i> <p>reach@skynetplacements.com</p></li>
          <% end %>
        </ul>
    </div>
    
    <!-- Social -->
    <div class="widget margin-top-30">
        <h3 class="margin-bottom-5">Social Media</h3>
        <ul class="social-icons">
            <li><a class="facebook" href="https://www.facebook.com/Skynet-Placements-126794617416629/" target="_blank"><i class="icon-facebook"></i></a></li>
            <li><a class="twitter" href="#" target="_blank"><i class="icon-twitter"></i></a></li>
            <li><a class="gplus" href="#"><i class="icon-gplus"></i></a></li>
            <li><a class="linkedin" href="https://www.linkedin.com/in/skynet-placements-76849569/" target="_blank"><i class="icon-linkedin"></i></a></li>
        </ul>
        <div class="clearfix"></div>
        <div class="margin-bottom-50"></div>
    </div>

</div>
</div>
<!-- Container / End -->

app/views/home/index.html.erb
<%= render :partial => "banner" %>

<!-- Content
================================================== -->

<!-- Categories -->
<div class="container">
	<div class="sixteen columns">
		<h3 class="margin-bottom-25">Popular Categories</h3>
		<ul id="popular-categories">
			<% @popular_categories.each do |category| %>
				<li><a href="<%= jobs_path(:category => category.id) %>"><i class="ln <%= category.get_icon %>"></i><%= category.name %></a></li>
			<% end %>
		</ul>

		<div class="clearfix"></div>
		<div class="margin-top-30"></div>

		<a href="<%= categories_path %>" class="button centered">Browse All Categories</a>
		<div class="margin-bottom-50"></div>
	</div>
</div>


<div class="container">
	
	<!-- Recent Jobs -->
	<div class="eleven columns">
	<div class="padding-right">
		<h3 class="margin-bottom-25">Recent Jobs</h3>
		<ul class="job-list">
			<%= render :partial => "recent_job", :collection => @recent_jobs %>
		</ul>
		<a href="<%= jobs_path %>" class="button centered"><i class="fa fa-plus-circle"></i> Show More Jobs</a>
		<div class="margin-bottom-55"></div>
	</div>
	</div>

	<!-- Job Spotlight -->
	<div class="five columns">
		<h3 class="margin-bottom-5">Job Spotlight</h3>

		<!-- Navigation -->
		<div class="showbiz-navigation">
			<div id="showbiz_left_1" class="sb-navigation-left"><i class="fa fa-angle-left"></i></div>
			<div id="showbiz_right_1" class="sb-navigation-right"><i class="fa fa-angle-right"></i></div>
		</div>
		<div class="clearfix"></div>
		
		<!-- Showbiz Container -->
		<div id="job-spotlight" class="showbiz-container">
			<div class="showbiz" data-left="#showbiz_left_1" data-right="#showbiz_right_1" data-play="#showbiz_play_1" >
				<div class="overflowholder">
					<ul>
						<%= render :partial => "spotlight", :collection => @spotlight_jobs %>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>

	</div>
</div>


<!-- Testimonials -->
<div id="testimonials">
	<!-- Slider -->
	<div class="container">
		<div class="sixteen columns">
			<div class="testimonials-slider">
				  <ul class="slides">
				    <li>
				      <p>
				      	It was a pleasure to have an association with a customer like you. I truly appreciate your Services. Its because of your reference that we have got so many trustworthy clients. Even my team members also appreciate the way you speak to them.
				      	<span>
				      		<i class="fa fa-star" aria-hidden="true"></i>
				      		<i class="fa fa-star" aria-hidden="true"></i>
				      		<i class="fa fa-star" aria-hidden="true"></i>
				      		<i class="fa fa-star" aria-hidden="true"></i>
				      		<i class="fa fa-star" aria-hidden="true"></i>
				      		<br />
				      		Brajesh Talati
				      		<br />
				      		HR Executive - Rubamin Ltd
				      	</span>
				      </p>
				    </li>

				    <li>
				      <p>Skynet placement is a professional agency which provide holistic services under one roof on all facets of HR. Understanding the requirement  of the position, providing the suitable CVs, organizing and coordinating the interviews and meeting the challenge of lead time of the recruitment of the organization, is the quality aspect which Skynet placement always meets. My best wishes to you and your staff.
				      <span>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<br />
				      	Sanjeev Kumar <br />
				      	Head HR - Larsen &amp; Toubro Limited
				      </span></p>
				    </li>
				    
				    <li>
				      <p>Satisfied with Skynet Team services.
				      <span>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<br />
				      	Harit Patel
				      	<br />
				      	CASME Industrial Park Development (India)Pvt. Ltd.
				      </span></p>
				    </li>

				    <li>
				      <p>Skynet is working with Narayan since long. In terms of Quality of your service we don't have any doubts so we rate you as 4 Four Star. The rating is all because of you and your excellent team member's support and skill in recruiting. 
				      <span>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star-o" aria-hidden="true"></i>
				      	<br />
				      	Dimple Patel
				      	<br />
				      	HR Officer - Narayan Powertech Pvt Ltd
				      </span></p>
				    </li>

				    <li>
				      <p>We have received great support from you and your team as our Recruitment partners.
				      <span>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star" aria-hidden="true"></i>
				      	<i class="fa fa-star-o" aria-hidden="true"></i>
				      	<br />
				      	Sailee Chandgude
				      	<br />
				      	Sr. Manager- Recruitment - Godrej Boy &amp; Company
				      </span></p>
				    </li>

				  </ul>
			</div>
		</div>
	</div>
</div>

app/views/home/new.html.erb
this is a new file