config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # site root

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/#{routes_name}.rb")))
  end

  root 'home#index'
  
  get "about_us", to: "home#about_us"
  get "contact_us", to: "home#contact_us"
  get "our_team", to: "home#our_team"
  get "categories", to: "home#categories"
  get "privacy_policy", to: "home#privacy_policy"

  resources :home do 
    collection do 
      get "about_us"
      get "contact_us"
      post "send_mail"
      get "our_team"
      get "categories"
      get "privacy_policy"
    end
  end

  # resources :sessions
  
  #sessions and sign up
  get "/users/login", to: "sessions#new", as: "login"
  get "/users/logout", to: "sessions#destroy", as: "logout"
  get "/users/resetpassword", to: "users#resetpassword", as: "resetpasswordform"
  post "/users/resetpassword", to: "users#resetpassword", as: "resetpassword"
  get "/users/resetp", to: "users#resetp"
  post "/users/updatepassword", to: "users#updatepassword", as: "updatepassword"
  get "/users/confirmation", to: "users#confirmation"
  get "/users/confirm", to: "users#confirm_user_email"
  get "/users/confirm_failure", to: "users#confirm_failure", as: "confirm_failure"
  get "/users/confirm_success", to: "users#confirm_success", as: "confirm_success"

  resources :users
  resources :sessions
  resources :jobs do 
    collection do 
      get "get_job_sub"
    end
    member do 
      get "bookmark"
    end
  end

  resources :resumes do
    member do
      get "bookmark"
    end
  end

  namespace :api do
    namespace :v1 do
      draw :api_routes      
    end
  end


  namespace :member do
    resources :profile do 
      collection do
        get "getselectdata"
      end
      member do 
        get "editresume"
      end
    end
    resources :jobs do 
      collection do
        get "get_job_sub"
        get "get_specialization"
        post "set_review_status"
        post "send_job_letter"
      end
      member do
        get "applications"
        post "application_info"
        get "fill_status"
        get "job_letter"
        delete "delete_job_application"
      end
    end
    resources :dashboards
  end

  namespace :admin do
    resources :dashboards do 
      collection do
        get "get_chart_data"
      end
    end
    resources :admin_profiles
    resources :employers
    resources :jobs do
      collection do
        get "get_job_subad"
        get "get_specializationad"
      end
    end
    resources :employees do
      collection do
        get "getselectdata"
        get "search"
      end
    end
    resources :settings do
      collection do 
        get "job_category_index"
        get "new_job_category"
        post "create_job_category"

        get "job_sub_category_index"
        get "new_job_sub_category"
        post "create_job_sub_category"

        get "ug_qualification_index"
        get "new_ug_qualification"
        post "create_ug_qualification"

        get "pg_qualification_index"
        get "new_pg_qualification"
        post "create_pg_qualification"

        get "phd_qualification_index"
        get "new_phd_qualification"
        post "create_phd_qualification"

        get "industry_index"
        get "new_industry"
        post "create_industry"

        get "country_index"
        get "new_country"
        post "create_country"

        get "location_index"
        get "new_location"
        post "create_location"

        get "designation_index"
        get "new_designation"
        post "create_designation"

      end
      member do
        get "edit_job_category"
        delete "delete_job_category"
        patch "update_job_category"

        get "edit_job_sub_category"
        delete "delete_job_sub_category"
        patch "update_job_sub_category"

        get "edit_ug_qualification"
        get "subjects"
        delete "delete_ug_qualification"
        patch "update_ug_qualification"

        get "edit_pg_qualification"
        get "specializations"
        delete "delete_pg_qualification"
        patch "update_pg_qualification"

        get "edit_phd_qualification"
        get "phd_specializations"
        delete "delete_phd_qualification"
        patch "update_phd_qualification"

        get "edit_industry"
        delete "delete_industry"
        patch "update_industry"

        get "edit_country"
        get "states"
        delete "delete_country"
        patch "update_country"

        get "edit_location"
        delete "delete_location"
        patch "update_location"

        get "edit_designation"
        delete "delete_designation"
        patch "update_designation"

      end
    end
  end

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < BackendController

  before_action :check_for_super_admin
# job category start

  def job_category_index
    @job_categories = JobCategory.all.asc(:name).page(params[:page]).per(15)
  end

  def new_job_category
    @update_errors = []
    if session[:admin_update_fail]
      @update_errors = session[:admin_update_fail]
      session.delete(:admin_update_fail)
    end
    @category = JobCategory.new 
    @icons = JSON.parse(File.read(File.join(Rails.root,"public","icons.json")))
  end

  def edit_job_category
    @update_errors = []
    if session[:admin_update_fail]
      @update_errors = session[:admin_update_fail]
      session.delete(:admin_update_fail)
    end
    @category = JobCategory.find(params[:id]) rescue nil
    @icons = JSON.parse(File.read(File.join(Rails.root,"public","icons.json")))
  end

  def create_job_category
    category = JobCategory.new(job_category_params)
    if category.save
      redirect_to job_category_index_admin_settings_path
    else
      session[:admin_update_fail] = category.errors.full_messages
      redirect_to new_job_category_admin_settings_path
    end
  end

  def delete_job_category
    category = JobCategory.find(params[:id]) rescue nil
    category.destroy if !category.nil?
     if params[:page]
        redirect_to job_category_index_admin_settings_path(:page => params[:page])
      else
         redirect_to job_category_index_admin_settings_path
      end
  end

  def update_job_category
    category = JobCategory.find(params[:id]) rescue nil
    if !category.nil? 
      if category.update_attributes(job_category_params)
        if params[:page]
          redirect_to job_category_index_admin_settings_path(:page => params[:page])
        else
           redirect_to job_category_index_admin_settings_path
        end
      else
        session[:admin_update_fail] = category.errors.full_messages
        redirect_to edit_job_category_admin_setting_path(cat, :page => params[:page])
      end
    end
  end
# job category end

# job sub category begin

  def job_sub_category_index
    if params[:parent_id].present?
      @job_sub_categories = JobSubCategory.where(:job_category_id => params[:parent_id]).asc(:name).page(params[:page]).per(15)
    else
      @job_sub_categories = JobSubCategory.all.asc(:name).page(params[:page]).per(15)
    end
  end

  def new_job_sub_category
    @update_errors = []
    if session[:admin_update_fail]
      @update_errors = session[:admin_update_fail]
      session.delete(:admin_update_fail)
    end
    @job_categories = JobCategory.all.asc(:name).collect{|jc| [jc.name, jc.id]}
    @category = JobSubCategory.new 
  end

  def edit_job_sub_category
    @update_errors = []
    if session[:admin_update_fail]
      @update_errors = session[:admin_update_fail]
      session.delete(:admin_update_fail)
    end
    @job_categories = JobCategory.all.asc(:name).collect{|jc| [jc.name, jc.id]}
    @category = JobSubCategory.find(params[:id]) rescue nil
  end

  def create_job_sub_category
    category = JobSubCategory.new(job_sub_category_params)
    if category.save
      redirect_to job_sub_category_index_admin_settings_path
    else
      session[:admin_update_fail] = category.errors.full_messages
      redirect_to new_job_sub_category_admin_settings_path
    end
  end

  def delete_job_sub_category
    category = JobSubCategory.find(params[:id]) rescue nil
    category.destroy if !category.nil?
    if params[:page]
      redirect_to job_sub_category_index_admin_settings_path(:page => params[:page])
    else
       redirect_to job_sub_category_index_admin_settings_path
    end
  end

  def update_job_sub_category
    category = JobSubCategory.find(params[:id]) rescue nil
    if !category.nil? 
      if category.update_attributes(job_sub_category_params)
        if params[:page]
          redirect_to job_sub_category_index_admin_settings_path(:page => params[:page])
        else
           redirect_to job_sub_category_index_admin_settings_path
        end
      else
        session[:admin_update_fail] = category.errors.full_messages
        redirect_to edit_job_sub_category_admin_setting_path(cat, :page => params[:page])
      end
    end
  end

  # job sub category end

  # ug qualifications begin

  def ug_qualification_index
    @ug_qualifications = UgQualification.all.asc(:name).page(params[:page]).per(15)
  end

  def new_ug_qualification
    @update_errors = []
    if session[:admin_update_fail]
      @update_errors = session[:admin_update_fail]
      session.delete(:admin_update_fail)
    end
    @ug_qualification = UgQualification.new
  end

  def edit_ug_qualification
    @update_errors = []
    if session[:admin_update_fail]
      @update_errors = session[:admin_update_fail]
      session.delete(:admin_update_fail)
    end
    @ug_qualification = UgQualification.find(params[:id])
  end

  def delete_ug_qualification
    ug_qualification = UgQualification.find(params[:id]) rescue nil
    ug_qualification.destroy if !ug_qualification.nil?
    if params[:page]
      redirect_to ug_qualification_index_admin_settings_path(:page => params[:page])
    else
       redirect_to ug_qualification_index_admin_settings_path
    end
  end

  def update_ug_qualification
    ug_qualification = UgQualification.find(params[:id]) rescue nil
    if !ug_qualification.nil?
      if ug_qualification.update_attributes(ug_qualification_params)
        if params[:page]
          redirect_to ug_qualification_index_admin_settings_path(:page => params[:page])
        else
          redirect_to ug_qualification_index_admin_settings_path
        end
      else
        session[:admin_update_fail] = ug_qualification.errors.full_messages
        redirect_to edit_ug_qualification_admin_setting_path(ug_qualification)
      end
    end
  end

  def create_ug_qualification
    ug_qualification = UgQualification.new(ug_qualification_params)
    if ug_qualification.save
      redirect_to ug_qualification_index_admin_settings_path
    else
      session[:admin_update_fail] = ug_qualification.errors.full_messages
      redirect_to new_ug_qualification_admin_settings_path
    end
  end

  def subjects
    @ug_qualification = UgQualification.find(params[:id])
    @subjects = @ug_qualification.subjects.asc(:name).page(params[:page]).per(15)
  end

  # ug qualifications end

  #pg qualifications begin 

  def pg_qualification_index
    @pg_qualifications = PgQualification.all.asc(:name).page(params[:page]).per(15)
  end

  def new_pg_qualification
    @update_errors = []
    if session[:admin_update_fail]
      @update_errors = session[:admin_update_fail]
      session.delete(:admin_update_fail)
    end
    @pg_qualification = PgQualification.new
  end

  def edit_pg_qualification
    @update_errors = []
    if session[:admin_update_fail]
      @update_errors = session[:admin_update_fail]
      session.delete(:admin_update_fail)
    end
    @pg_qualification = PgQualification.find(params[:id])
  end

  def delete_pg_qualification
    pg_qualification = PgQualification.find(params[:id]) rescue nil
    pg_qualification.destroy if !pg_qualification.nil?
    if params[:page]
      redirect_to pg_qualification_index_admin_settings_path(:page => params[:page])
    else
       redirect_to pg_qualification_index_admin_settings_path
    end
  end

  def update_pg_qualification
    pg_qualification = PgQualification.find(params[:id]) rescue nil
    if !pg_qualification.nil?
      if pg_qualification.update_attributes(pg_qualification_params)
        if params[:page]
          redirect_to pg_qualification_index_admin_settings_path(:page => params[:page])
        else
          redirect_to pg_qualification_index_admin_settings_path
        end
      else
        session[:admin_update_fail] = pg_qualification.errors.full_messages
        redirect_to edit_pg_qualification_admin_setting_path(pg_qualification)
      end
    end
  end

  def create_pg_qualification
    pg_qualification = PgQualification.new(pg_qualification_params)
    if pg_qualification.save
      redirect_to pg_qualification_index_admin_settings_path
    else
      session[:admin_update_fail] = pg_qualification.errors.full_messages
      redirect_to new_pg_qualification_admin_settings_path
    end
  end

  def specializations
    @pg_qualification = PgQualification.find(params[:id])
    @specializations = @pg_qualification.specializations.asc(:name).page(params[:page]).per(15)
  end

  # pg qualifications end

  # phd begin 

  def phd_qualification_index
    @phd_qualifications = PhdQualification.all.asc(:name).page(params[:page]).per(15)
  end

  def new_phd_qualification
    @update_errors = []
    if session[:admin_update_fail]
      @update_errors = session[:admin_update_fail]
      session.delete(:admin_update_fail)
    end
    @phd_qualification = PhdQualification.new
  end

  def edit_phd_qualification
    @update_errors = []
    if session[:admin_update_fail]
      @update_errors = session[:admin_update_fail]
      session.delete(:admin_update_fail)
    end
    @phd_qualification = PhdQualification.find(params[:id])
  end

  def delete_phd_qualification
    phd_qualification = PhdQualification.find(params[:id]) rescue nil
    phd_qualification.destroy if !phd_qualification.nil?
    if params[:page]
      redirect_to phd_qualification_index_admin_settings_path(:page => params[:page])
    else
       redirect_to phd_qualification_index_admin_settings_path
    end
  end

  def update_phd_qualification
    phd_qualification = PhdQualification.find(params[:id]) rescue nil
    if !phd_qualification.nil?
      if phd_qualification.update_attributes(phd_qualification_params)
        if params[:page]
          redirect_to phd_qualification_index_admin_settings_path(:page => params[:page])
        else
          redirect_to phd_qualification_index_admin_settings_path
        end
      else
        session[:admin_update_fail] = phd_qualification.errors.full_messages

app/views/admin/settings/_country_form.html.erb
<% if !@update_errors.blank? %>
	<div class="alert alert-error alert-block">
		<a class="close" data-dismiss="alert" href="#">×</a>
		<h4 class="alert-heading">Error!</h4>
			<% @update_errors.each do |error| %>
				<p><%= error %>.</p> 
			<% end %>
	</div>
<% end %>
<div class="control-group">
	<%= f.label :name, "Country Name", :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :name, :class => "span11", :placeholder => "India / Taiwan / Canada" %>
  </div>
</div>
<div class="control-group">
	<label class="sub-heading"><h4>State(s)</h4></label>
</div>
<div id="state-holder" class="inner-form-box">
		<div class="box-to-add-states">
	  <% @country.states.each_with_index do |state, i| %>
	    <%= f.fields_for :states, state, :child_index => i do |se| %>
	       <%= render :partial => "state_form", :locals => {:se => se, :i => i, :obj => state} %>
	    <% end %>
	  <% end %>
	  </div>
	  <div class="inner-form-box-add-btn">
	  	<button class="btn btn-info" id="add-state-btn">Add state</button>
	  	 <div class="box-to-clone">
	  		<%  new_object = f.object.send("states").build #rescue nil %>
      	<%= f.fields_for :states, new_object, :child_index => "XXX" do |se| %>
        	<%= render :partial => "state_form", :locals => {:se => se, :i => "XXX", :obj => new_object} %>
      	<% end %>
	  	</div>
	  </div>
	</div>
<div class="form-actions">
	<% if params[:page] %>
		<input type="hidden" value="<%= params[:page] %>" name="page" >
	<% end %>
  <%= f.submit "Save", :class => "btn btn-success" %>
	<a href="<%= country_index_admin_settings_path(:page => params[:page]) %>" class="btn">Cancel</a>
</div>

<script type="text/javascript">
	var stateHolder = $("#state-holder .box-to-add-states");
	$("button#add-state-btn").on("click",function(){
		var clonebox = $(this).parent().find(".box-to-clone").clone(),
				totalEnteries = stateHolder.find(".inner-fields-holder").length,
				old_id = new RegExp("XXX", "g"),
				newstatebox = clonebox.html().replace(old_id, totalEnteries);
				
		$(".box-to-add-states").append(newstatebox);
		return false;
	})

		$("body").on("click",".remove-box", function(){
			if($(this).parent().parent().hasClass("stored-box")){
				if(confirm("Are you sure?")){
					$(this).find("input[type=hidden]").val("1");
					$(this).parents(".inner-fields-holder").slideUp();
				}
			}else{
				$(this).parents(".inner-fields-holder").slideUp(function(){
					$(this).remove();
				});
			}
			return false;
		})

	$("form.admin-ug-qualification-form").on("submit",function(){
		$(".box-to-clone").remove();
	})
</script>

app/views/admin/settings/_job_sub_category_form.html.erb
<% content_for :page_specific_css do %>
	<link rel="stylesheet" href="/assets/backend/select2.css">
	<link rel="stylesheet" href="/assets/backend/uniform.css">
<% end %>
<% if !@update_errors.blank? %>
	<div class="alert alert-error alert-block">
		<a class="close" data-dismiss="alert" href="#">×</a>
		<h4 class="alert-heading">Error!</h4>
			<% @update_errors.each do |error| %>
				<p><%= error %>.</p> 
			<% end %>
	</div>
<% end %>
<div class="control-group">
	<%= f.label :job_category_id, "Parent Category", :class => "control-label" %>
  <div class="controls">
    <%= f.select :job_category_id, @job_categories, {:selected => (@category.job_category_id rescue ""), :prompt => "Select Job Category"}, {:class => "span11"} %>
  </div>
</div>
<div class="control-group">
	<%= f.label :name, "Sub Category Name", :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :name, :class => "span11", :placeholder => "Business, Computer, IT" %>
  </div>
</div>
<div class="form-actions">
	<% if params[:page] %>
		<input type="hidden" value="<%= params[:page] %>" name="page" >
	<% end %>
	<%= f.hidden_field :created_by, :value =>  current_user.id %>
  <%= f.submit "Save", :class => "btn btn-success" %>
	<a href="<%= job_sub_category_index_admin_settings_path(:page => params[:page]) %>" class="btn">Cancel</a>
</div>

app/views/admin/settings/_location_form.html.erb
<% if !@update_errors.blank? %>
	<div class="alert alert-error alert-block">
		<a class="close" data-dismiss="alert" href="#">×</a>
		<h4 class="alert-heading">Error!</h4>
			<% @update_errors.each do |error| %>
				<p><%= error %>.</p> 
			<% end %>
	</div>
<% end %>
<div class="control-group">
	<%= f.label :name, "Location Name", :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :name, :class => "span11", :placeholder => "Vadodara, Mumbai, Delhi " %>
  </div>
</div>

<div class="form-actions">
	<% if params[:page] %>
		<input type="hidden" value="<%= params[:page] %>" name="page" >
	<% end %>
  <%= f.submit "Save", :class => "btn btn-success" %>
	<a href="<%= location_index_admin_settings_path(:page => params[:page]) %>" class="btn">Cancel</a>
</div>

app/views/admin/settings/_state_form.html.erb
<div class="inner-fields-holder">
	<div class="inner-box-header <%= i == "XXX" ? "" : "stored-box" %>">
		<span class="delete-object">
			<a class="remove-box" href="#">
				<i class="icon-remove"></i>
				<% if i != "XXX" %>
					<%= se.hidden_field :_destroy, :value => nil, :class => 'should_destroy' %>
				<% end %>
			</a>
		</span>
	</div>
	<div class="control-group">
		<%= se.label :name, "Name", :class => "control-label" %>
	  <div class="controls">
	    <%= se.text_field :name, :class => "span11", :placeholder => "Gujarat / Maharashtra" %>
	  </div>
	</div>
</div>

app/views/admin/settings/_subject_form.html.erb
<div class="inner-fields-holder">
	<div class="inner-box-header <%= i == "XXX" ? "" : "stored-box" %>">
		<span class="delete-object">
			<a class="remove-box" href="#">
				<i class="icon-remove"></i>
				<% if i != "XXX" %>
					<%= se.hidden_field :_destroy, :value => nil, :class => 'should_destroy' %>
				<% end %>
			</a>
		</span>
	</div>
	<div class="control-group">
		<%= se.label :name, "Name", :class => "control-label" %>
	  <div class="controls">
	    <%= se.text_field :name, :class => "span11", :placeholder => "Chemistry, Math, Biology" %>
	  </div>
	</div>
</div>

app/views/admin/settings/edit_location.html.erb
<% content_for :breadcrumbs do %>
	<a class="tip-bottom" href="<%= location_index_admin_settings_path %>" data-original-title="Location">Location</a>
	<a href="#" class="current" onclick="return false;">Edit</a>
<% end %>
<% content_for :page_title do %>
  Location
<% end %>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- <div class="span6"> -->
	  	<div class="widget-box">
	    	<div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
	      	<h5>Edit Location for <%= @location.name %></h5>
	    	</div>
	    	<div class="widget-content nopadding">
					<%= form_for @location, :url => {:action => "update_location"}, :html => {:class => "form-horizontal admin-ug-qualification-form"} do |f| %>
						<%= render :partial => "location_form", :locals => {:f => f} %>
					<% end %>
				</div>
			</div>
		<!-- </div> -->
	</div>
</div>

app/views/admin/settings/job_sub_category_index.html.erb
	<%= csrf_meta_tags %>
	<% content_for :breadcrumbs do %>
		<a href="#" class="current" onclick="return false;">Job Sub Categories</a>
	<% end %>
	<% content_for :page_title do %>
   Job Sub Categories
  <% end %>
	<div class="container-fluid">
		<hr>
		<div class="row-fluid">
			<div class="span12">
				<div class="widget-box">
				  <div class="widget-title"> <span class="icon"> <i class="icon-cogs"></i> </span>
				    <h5>Job Sub Categories</h5>
				  </div>
				  <div class="widget-content nopadding">
				    <table class="table table-bordered table-striped">
				      <thead>
				        <tr>
				          <th>Name</th>
				          <th>Parent Category</th>
				          <th>Created On</th>
				          <th>Created By</th>
				          <th>Actions</th>
				        </tr>
				      </thead>
				      <tbody>
				      	<% @job_sub_categories.each_with_index do |cat,i| %>
				      		<tr class="<%= i%2 != 0 ? "even" : "odd" %>">
				      			<td><%= cat.name  %></td>
				      			<td><a href="<%= job_sub_category_index_admin_settings_path(:parent_id => cat.job_category.id) %>"><%= cat.job_category.name  %></a></td>
				      			<td><%= cat.created_at.strftime("%d/%m/%Y") %></td>
				      			<td><%= cat.created_user_name %></td>
				      			<td> 
				      				<a href="<%= edit_job_sub_category_admin_setting_path(cat, :page=>params[:page]) %>" class="btn btn-mini btn-primary">Edit</a>
				      				<%= link_to "Delete", delete_job_sub_category_admin_setting_path(cat, :page=>params[:page]), :method => :delete, :class => "btn btn-mini btn-danger", :data => {:confirm => "All jobs under this sub category will be deleted. Are you sure that you want to continue?"} %>
				      			</td>
				      		</tr>
				      	<% end %>
				     	</tbody>
				    </table>
				  </div>
				</div>
			</div>
		</div>
		<%= link_to "Add Sub Category", new_job_sub_category_admin_settings_path, class: "btn btn-primary" %>
		<% if params[:parent_id].present? %>
			<a href="#" onclick="window.history.back();" class="btn btn-info">Go Back</a>
		<% end %>
	</div>
<%=
  content_tag :div, class: "bottomnav clearfix" do
    content_tag :div, paginate(@job_sub_categories), class: "pagination pagination-centered"
  end
%>

app/views/admin/settings/new_industry.html.erb
<% content_for :breadcrumbs do %>
	<a class="tip-bottom" href="<%= industry_index_admin_settings_path %>" data-original-title="Industry">Industry</a>
	<a href="#" class="current" onclick="return false;">New</a>
<% end %>
<% content_for :page_title do %>
  Industry
<% end %>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- <div class="span6"> -->
	  	<div class="widget-box">
	    	<div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
	      	<h5>New Industry</h5>
	    	</div>
	    	<div class="widget-content nopadding">
					<%= form_for @industry, :url => {:action => "create_industry"}, :html => {:class => "form-horizontal admin-ug-qualification-form"} do |f| %>
						<%= render :partial => "industry_form", :locals => {:f => f} %>
					<% end %>
				</div>
			</div>
		<!-- </div> -->
	</div>
</div>

app/views/admin/settings/new_location.html.erb
<% content_for :breadcrumbs do %>
	<a class="tip-bottom" href="<%= location_index_admin_settings_path %>" data-original-title="Location">Location</a>
	<a href="#" class="current" onclick="return false;">New</a>
<% end %>
<% content_for :page_title do %>
  Location
<% end %>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- <div class="span6"> -->
	  	<div class="widget-box">
	    	<div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
	      	<h5>New Location</h5>
	    	</div>
	    	<div class="widget-content nopadding">
					<%= form_for @location, :url => {:action => "create_location"}, :html => {:class => "form-horizontal admin-ug-qualification-form"} do |f| %>
						<%= render :partial => "location_form", :locals => {:f => f} %>
					<% end %>
				</div>
			</div>
		<!-- </div> -->
	</div>
</div>

app/views/admin/settings/pg_qualification_index.html.erb
	<%= csrf_meta_tags %>
	<% content_for :breadcrumbs do %>
		<a href="#" class="current" onclick="return false;">Post Graduate Qualifications</a>
	<% end %>
	<% content_for :page_title do %>
   Post Graduate Qualifications
  <% end %>
	<div class="container-fluid">
		<hr>
		<div class="row-fluid">
			<div class="span12">
				<div class="widget-box">
				  <div class="widget-title"> <span class="icon"> <i class="icon-cogs"></i> </span>
				    <h5>Post Graduate Qualifications</h5>
				  </div>
				  <div class="widget-content nopadding">
				    <table class="table table-bordered table-striped">
				      <thead>
				        <tr>
				          <th>Name</th>
				          <th>Created On</th>
				          <th>Created By</th>
				          <th>Actions</th>
				        </tr>
				      </thead>
				      <tbody>
				      	<% @pg_qualifications.each_with_index do |u,i| %>
				      		<tr class="<%= i%2 != 0 ? "even" : "odd" %>">
				      			<td><a href="<%= specializations_admin_setting_path(u) %>"><%= u.name  %></a></td>
				      			<td><%= u.created_at.strftime("%d/%m/%Y") %></td>
				      			<td><%= u.created_user_name %></td>
				      			<td> 
				      				<a href="<%= edit_pg_qualification_admin_setting_path(u, :page=>params[:page]) %>" class="btn btn-mini btn-primary">Edit</a>
				      				<%= link_to "Delete", delete_pg_qualification_admin_setting_path(u, :page=>params[:page]), :method => :delete, :class => "btn btn-mini btn-danger", :data => {:confirm => "Are you sure?"} %>
				      			</td>
				      		</tr>
				      	<% end %>
				     	</tbody>
				    </table>
				  </div>
				</div>
			</div>
		</div>
		<%= link_to "Add Qualification", new_pg_qualification_admin_settings_path, class: "btn btn-primary" %>
	</div>
<%=
  content_tag :div, class: "bottomnav clearfix" do
    content_tag :div, paginate(@pg_qualifications), class: "pagination pagination-centered"
  end
%>